name: DontStarveFinalStorm
version: 1.0
author: Noverita
main: me.noverita.finalstorm.Main
api-version: 1.13
commands:
  finalestorm:
    description: Don't touch this.
    usage: /finalestorm
    default: op
  finalemarktunnel:
    description: Don't touch this.
    usage: /finalemarktunnel
    default: op
  finaleopen:
    description: Don't touch this.
    usage: /finaleopen
    default: op